#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
$status = (require_once __DIR__.'/bootstrap/app.php')
    ->handleCommand(new ArgvInput);

// Run the command to clear the application cache to resolve potential caching issues.
$status = (require_once __DIR__.'/bootstrap/app.php')
    ->handleCommand(new ArgvInput(['command' => 'cache:clear']));

exit($status);
